version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: raw_observations
      - name: raw_stations
      - name: raw_inventory
      - name: raw_countries
      - name: configured_stations
      - name: element_metadata
      - name: quality_flag_metadata